var ForgottenCraftFunction = [];

BloodWolf = [ForgottenCraftFunction , ModPE , Level , Player , Entity , Item , Block , Server];
_ForgottenCraft0Function_ = 0;
_ForgottenCraft1Function_ = 1;
_ForgottenCraft2Function_ = 2;
_ForgottenCraft3Function_ = 3;
_ForgottenCraft4Function_ = 4;
_ForgottenCraft5Function_ = 5;
_ForgottenCraft6Function_ = 6;

ForgottenCraft = function(_Forgotten0Craft_ , _Forgotten1Craft_){
 return _Forgotten0Craft_[_Forgotten1Craft_];
}
